/**
 * Graphic T's display — one entry per shirt, in strip order.
 *
 * `flat` is the 2D cutout shown in the strip (and on the stage when there is
 * no 3D model yet). `print` is the shirt's baked base-colour texture for the
 * shared 3D tee (public/apparel/t-shirts/tshirt.glb); shirts without one show
 * their flat image on the stage until a GLB is supplied.
 *
 * Assets are generated by scripts/build-tshirt-assets.mjs (3D) from the
 * sources in assets/projects/apperal/t-shirts/.
 */
export type GraphicTee = {
  slug: string;
  name: string;
  flat: string;
  print?: string;
};

const flat = (slug: string) => `/apparel/t-shirts/flat/${slug}.webp`;
const print = (slug: string) => `/apparel/t-shirts/prints/${slug}.webp`;

export const TSHIRT_MODEL = "/apparel/t-shirts/tshirt.glb";

/** A shirt with both a flat cutout and a 3D print (same slug for both). */
const tee = (slug: string, name: string): GraphicTee => ({ slug, name, flat: flat(slug), print: print(slug) });

export const graphicTees: GraphicTee[] = [
  tee("morality", "Morality"),
  tee("hardcore-mentality", "Hardcore Mentality"),
  tee("conformity", "Conformity"),
  tee("seven-deadly-sins", "7 Deadly Sins"),
  tee("abaddon", "Abaddon"),
  tee("burden-of-intellect", "Burden of Intellect"),
  tee("nod-mami", "Nod Mami"),
  tee("essentials", "Essentials"),
  tee("ferocious", "Ferocious"),
  tee("sheep", "Sheep"),
  tee("the-eyes-chico", "The Eyes Chico"),
  tee("the-tempest-of-iron", "The Tempest of Iron"),
  tee("vision", "Vision"),
  tee("damaged-goods", "Damaged Goods"),
  tee("speak-up", "Speak Up"),
];
