import type { StaticImageData } from "next/image";

import arcade from "../../../assets/projects/Sticker Illustrations/arcade_sticker.png";
import babyBoomers from "../../../assets/projects/Sticker Illustrations/BabyBoomers-Sticker-Front.png";
import blushingDuck from "../../../assets/projects/Sticker Illustrations/Blushing Duck-Sticker-Front.png";
import cookies from "../../../assets/projects/Sticker Illustrations/Cookies Sticker-Front.png";
import illunis from "../../../assets/projects/Sticker Illustrations/Illunis Sticker-Front.png";
import lvGlock from "../../../assets/projects/Sticker Illustrations/LV Sticker.png";
import miamiViceTiger from "../../../assets/projects/Sticker Illustrations/Miami Vice Tiger C-Drip Sticker-Front.png";
import rhodesianTiger from "../../../assets/projects/Sticker Illustrations/RhodesianTiger-Sticker-Front.png";
import medusa from "../../../assets/projects/Sticker Illustrations/Sticker-5-Medusa-Front.png";
import cyberSkull from "../../../assets/projects/Sticker Illustrations/StickerFront-CODRedTiger.png";
import subzero from "../../../assets/projects/Sticker Illustrations/Subzero Sticker.png";
import hornedSkull from "../../../assets/projects/Sticker Illustrations/violet_sticker.png";
import generic1 from "../../../assets/projects/Sticker Illustrations/Sticker Front.png";
import generic2 from "../../../assets/projects/Sticker Illustrations/Sticker- Front.png";
import generic3 from "../../../assets/projects/Sticker Illustrations/Sticker-6- Front.png";
import generic4 from "../../../assets/projects/Sticker Illustrations/Sticker-Front (1).png";
import generic5 from "../../../assets/projects/Sticker Illustrations/Sticker-Front (2).png";
import generic6 from "../../../assets/projects/Sticker Illustrations/Sticker-Front 1.png";
import generic7 from "../../../assets/projects/Sticker Illustrations/Sticker-Front Dob.png";
import generic8 from "../../../assets/projects/Sticker Illustrations/Sticker-Front Mag Cut.png";
import generic9 from "../../../assets/projects/Sticker Illustrations/Sticker-Front N.png";
import generic10 from "../../../assets/projects/Sticker Illustrations/Sticker-Front p.png";
import generic11 from "../../../assets/projects/Sticker Illustrations/Sticker-Front SW.png";
import generic12 from "../../../assets/projects/Sticker Illustrations/Sticker-Front.png";
import generic13 from "../../../assets/projects/Sticker Illustrations/Sticker-SB-Front.png";

/**
 * The sticker archive, rebuilt around a REAL three.js cylinder (see
 * StickerScene.tsx) instead of a DOM/CSS warp illusion. Every sticker here
 * is a fixed placement on ONE continuous cylindrical surface — a (u, v)
 * coordinate around the circumference and down a tall vertical texture atlas
 * — not an independently timed/animated element. The whole surface rotates
 * and travels vertically as one rigid object; stickers enter/leave frame
 * purely because the physical surface is moving past a fixed camera.
 *
 * To add a sticker: drop the transparent PNG into
 * `assets/projects/Sticker Illustrations/`, import it, add it to
 * `rawStickers`, and give it a row in MANUAL_LAYOUT below.
 *
 * Placement is HAND-AUTHORED (MANUAL_LAYOUT), not generated by a scatter
 * algorithm — the reference reads as a real densely-covered pole, which a
 * mathematically even distribution doesn't produce. Every entry is grouped
 * into one of four vertical clusters (5–7 stickers each) with a short gap
 * between clusters, sizes/rotations/overlap chosen by eye per item.
 */
export type SizeTier = "small" | "medium" | "large";

export interface StickerPlacement {
  src: StaticImageData;
  alt: string;
  /** 0–1 around the cylinder's circumference. Fixed forever — this is a point on the physical surface, not a moment in time. */
  u: number;
  /** 0–1 down the tall texture atlas (0 = top of the pole's printed surface). */
  v: number;
  /** Sticker's on-atlas width as a fraction of the full atlas width (== full circumference). Derived from sizeTier via WIDTH_FRAC_BY_TIER. */
  widthFrac: number;
  /** Small deterministic rotation jitter, degrees — reads as hand-applied rather than machine-perfect. */
  rotationDeg: number;
  sizeTier: SizeTier;
}

type StickerInput = { src: StaticImageData; alt: string; sizeTier?: SizeTier; group?: string };

const rawStickers: StickerInput[] = [
  { src: miamiViceTiger, alt: "Miami Vice tiger sticker", group: "tigers" },
  { src: rhodesianTiger, alt: "Rhodesian tiger sticker", group: "tigers" },
  { src: medusa, alt: "Fake Love Medusa sticker" },
  { src: cyberSkull, alt: "Warrior cyber-skull sticker", group: "skulls" },
  { src: hornedSkull, alt: "Horned skull sticker", group: "skulls" },
  { src: cookies, alt: "Camo skull sticker", group: "skulls" },
  { src: subzero, alt: "Warrior shield sticker" },
  { src: lvGlock, alt: "LV Warrior pistol sticker" },
  { src: arcade, alt: "Arcade cabinet sticker" },
  { src: babyBoomers, alt: "Pop-art warrior sticker" },
  { src: blushingDuck, alt: "Blushing duck sticker" },
  { src: illunis, alt: "Illunis sticker" },
  { src: generic1, alt: "Graphic sticker" },
  { src: generic2, alt: "Graphic sticker" },
  { src: generic3, alt: "Graphic sticker" },
  { src: generic4, alt: "Graphic sticker" },
  { src: generic5, alt: "Graphic sticker" },
  { src: generic6, alt: "Graphic sticker" },
  { src: generic7, alt: "Graphic sticker" },
  { src: generic8, alt: "Graphic sticker" },
  { src: generic9, alt: "Graphic sticker" },
  { src: generic10, alt: "Graphic sticker" },
  { src: generic11, alt: "Graphic sticker" },
  { src: generic12, alt: "Graphic sticker" },
  { src: generic13, alt: "Graphic sticker" },
];

/**
 * Target on-screen width as a fraction of the VISIBLE pole width, for a
 * sticker centred at dead-front. Converted to widthFrac (fraction of full
 * circumference / atlas width) below via: a front-facing sticker of angular
 * width θ spans ≈ R·θ on screen; visible pole width = 2R; so R·θ = target·2R
 * => θ = 2·target, and widthFrac = θ / 2π = target / π.
 */
const TARGET_SCREEN_FRACTION: Record<SizeTier, number> = {
  small: 0.215, // 18–25%
  medium: 0.34, // 28–40%
  large: 0.485, // 42–55%
};

const WIDTH_FRAC_BY_TIER: Record<SizeTier, number> = {
  small: TARGET_SCREEN_FRACTION.small / Math.PI,
  medium: TARGET_SCREEN_FRACTION.medium / Math.PI,
  large: TARGET_SCREEN_FRACTION.large / Math.PI,
};

function normalizeDeg(a: number) {
  return ((a % 360) + 360) % 360;
}

/**
 * Hand-authored placement, one row per rawStickers entry (same order/index).
 * `angleDeg` is this sticker's FIXED position on the surface (converted to
 * u below) — chosen, per cluster, so that ROTATION_TURNS·360° of rotation
 * carries that cluster's angleDeg range to dead-front right around the
 * scroll progress it's meant to be seen at (cluster A ≈ p0, B ≈ p0.33,
 * C ≈ p0.66, D ≈ p1). `v` is chosen the same way against
 * VERTICAL_TRAVEL_WORLD/INITIAL_Y_OFFSET so each cluster is centred in the
 * camera right as it becomes "current" — spaced far enough apart (in both
 * v and angle) that mostly one cluster is in frame at a time, not two piled
 * on top of each other. Angles are TIGHT within each cluster (~20–25° core)
 * so the cluster reads as one dense group rather than spreading wide enough
 * to bleed into its neighbour; one or two items per cluster sit well outside
 * that core specifically to wrap around the curved edge.
 *
 * Four clusters of 7/6/6/6 — deliberately close/overlapping angles and
 * varied sizes within a cluster, some overlap, a real sticker-bombed pole
 * rather than an even scatter.
 */
const MANUAL_LAYOUT: { angleDeg: number; v: number; sizeTier: SizeTier; rotationDeg: number }[] = [
  // Cluster A — front, visible at rest (p≈0). Tight core -10..12°, two
  // outliers at -40/39 wrap around the left/right edge at rest.
  { angleDeg: -40, v: 0.7249, sizeTier: "large", rotationDeg: -6 }, // 0 miamiViceTiger — left edge, wraps in
  { angleDeg: -10, v: 0.6749, sizeTier: "medium", rotationDeg: 8 }, // 1 rhodesianTiger
  { angleDeg: -4, v: 0.7549, sizeTier: "medium", rotationDeg: -4 }, // 2 medusa
  { angleDeg: 2, v: 0.6599, sizeTier: "small", rotationDeg: 10 }, // 3 cyberSkull
  { angleDeg: 7, v: 0.7349, sizeTier: "medium", rotationDeg: -9 }, // 4 hornedSkull
  { angleDeg: 12, v: 0.6849, sizeTier: "medium", rotationDeg: 5 }, // 5 cookies
  { angleDeg: 39, v: 0.7649, sizeTier: "large", rotationDeg: -3 }, // 6 subzero — right edge, wraps in

  // Cluster B — arrives around p≈0.33.
  { angleDeg: -60, v: 0.5743, sizeTier: "medium", rotationDeg: 7 }, // 7 lvGlock — left edge outlier
  { angleDeg: -48, v: 0.5442, sizeTier: "large", rotationDeg: -8 }, // 8 arcade
  { angleDeg: -42, v: 0.5943, sizeTier: "medium", rotationDeg: 4 }, // 9 babyBoomers
  { angleDeg: -35, v: 0.5542, sizeTier: "small", rotationDeg: -11 }, // 10 blushingDuck
  { angleDeg: -29, v: 0.5793, sizeTier: "medium", rotationDeg: 6 }, // 11 illunis
  { angleDeg: -18, v: 0.5342, sizeTier: "medium", rotationDeg: -5 }, // 12 generic1 — right edge outlier

  // Cluster C — arrives around p≈0.66.
  { angleDeg: -98, v: 0.4266, sizeTier: "medium", rotationDeg: -7 }, // 13 generic2 — left edge outlier
  { angleDeg: -86, v: 0.3965, sizeTier: "large", rotationDeg: 9 }, // 14 generic3
  { angleDeg: -80, v: 0.4366, sizeTier: "medium", rotationDeg: -4 }, // 15 generic4
  { angleDeg: -73, v: 0.4065, sizeTier: "small", rotationDeg: 6 }, // 16 generic5
  { angleDeg: -67, v: 0.4216, sizeTier: "medium", rotationDeg: -10 }, // 17 generic6
  { angleDeg: -56, v: 0.3865, sizeTier: "medium", rotationDeg: 3 }, // 18 generic7 — right edge outlier

  // Cluster D — arrives around p≈1.0.
  { angleDeg: -137, v: 0.2686, sizeTier: "medium", rotationDeg: -6 }, // 19 generic8 — left edge outlier
  { angleDeg: -125, v: 0.2435, sizeTier: "large", rotationDeg: 8 }, // 20 generic9
  { angleDeg: -119, v: 0.2736, sizeTier: "medium", rotationDeg: -3 }, // 21 generic10
  { angleDeg: -112, v: 0.2535, sizeTier: "small", rotationDeg: 10 }, // 22 generic11
  { angleDeg: -106, v: 0.2385, sizeTier: "medium", rotationDeg: -8 }, // 23 generic12
  { angleDeg: -95, v: 0.2636, sizeTier: "medium", rotationDeg: 5 }, // 24 generic13 — right edge outlier
];

function buildPlacements(inputs: StickerInput[]): StickerPlacement[] {
  return inputs.map((s, i) => {
    const layout = MANUAL_LAYOUT[i];
    const tier = s.sizeTier ?? layout.sizeTier;
    return {
      src: s.src,
      alt: s.alt,
      u: normalizeDeg(layout.angleDeg) / 360,
      v: layout.v,
      widthFrac: WIDTH_FRAC_BY_TIER[tier],
      rotationDeg: layout.rotationDeg,
      sizeTier: tier,
    };
  });
}

export const stickerPlacements: StickerPlacement[] = buildPlacements(rawStickers);
export const STICKER_COUNT = stickerPlacements.length;

/**
 * Sticker texture atlas resolution — wraps the FULL circumference
 * horizontally. Height (and the resulting CYLINDER_WORLD_HEIGHT below) is
 * sized for two things at once, not just cluster spacing: the pole must
 * ALSO stay taller than the camera frustum at every scroll position — with
 * MANUAL_LAYOUT's clusters packed for good density, the printed surface
 * genuinely needs this much plain-metal margin above/below the clusters so
 * the open cylinder's top/bottom edge never scrolls into frame.
 */
export const ATLAS_WIDTH = 2048;
export const ATLAS_HEIGHT = 3260;

/** Cylinder radius, world units (arbitrary scene scale). */
export const CYLINDER_RADIUS = 1.6;
const CIRCUMFERENCE = 2 * Math.PI * CYLINDER_RADIUS;

/**
 * Derived (not hand-picked) so the atlas maps onto the cylinder at a
 * uniform, undistorted scale in both directions — same px-per-world-unit
 * horizontally and vertically — otherwise sticker artwork would stretch.
 */
export const CYLINDER_WORLD_HEIGHT = (ATLAS_HEIGHT / ATLAS_WIDTH) * CIRCUMFERENCE;

/** The pole occupies ~46% of the frame width at rest — a touch larger than before so the artwork reads with more impact. */
export const POLE_FRAME_FRACTION = 0.46;

/**
 * 115° total rotation across the whole scroll section — within the 90–140°
 * target. MANUAL_LAYOUT's cluster angleDeg values are chosen backwards from
 * this exact figure (see its doc comment) so each cluster reaches dead-front
 * at the scroll progress it's meant to be seen at.
 */
export const ROTATION_TURNS = 115.2 / 360;

/**
 * Vertical travel + starting offset across the whole scroll section, chosen
 * together in WORLD UNITS (not as a round fraction of height) to hit two
 * targets simultaneously:
 *  1. Cluster centres land at the camera roughly one-per-viewport as scroll
 *     progresses (INITIAL_Y_OFFSET puts cluster A at the camera at p=0;
 *     VERTICAL_TRAVEL_WORLD carries that point down to cluster D by p=1,
 *     with B/C landing in between at p≈0.33/0.66) — spaced far enough apart
 *     that mostly one cluster is in frame at a time, not several piled up.
 *  2. The pole's own top/bottom edge stays outside the camera frustum at
 *     every scroll position (checked against CYLINDER_WORLD_HEIGHT above)
 *     — this is what actually determined how tall the atlas needed to be,
 *     not an arbitrary "taller is safer" guess.
 * In absolute terms this travel is less than the previous pass's (~66%).
 *
 * SIGN NOTE: with the sticker texture's default flipY (kept true so artwork
 * stays upright — see useStickerAtlasTexture), CylinderGeometry's mesh v=0
 * samples the BOTTOM of what we draw, not the top, so world Y from a given
 * `v` is `groupY + (0.5 - v) * H`, not `groupY + (v - 0.5) * H`. These two
 * constants are the negation of what the naive (v - 0.5) formula would give
 * — that's deliberate, not a rounding choice.
 */
export const INITIAL_Y_OFFSET = 3.43;
export const VERTICAL_TRAVEL_WORLD = -7.32;

/** Radial smoothness — within the requested 64–128 range. */
export const RADIAL_SEGMENTS = 96;
